param(
    [double]$DurationHours = 8,
    [int]$IntervalSeconds = 5,
    [string]$ApiBaseUrl = 'http://127.0.0.1:8080',
    [string]$SessionCookie = $env:ABUZAR_PERF_SESSION_COOKIE,
    [string]$ItemLegacyId = 'ITEM-000001',
    [string]$GodownId = '90000000-0000-0000-0000-000000000201',
    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'
if ($DurationHours -le 0 -or $DurationHours -gt 24) {
    throw 'DurationHours must be greater than 0 and no more than 24.'
}
if ($IntervalSeconds -lt 1 -or $IntervalSeconds -gt 3600) {
    throw 'IntervalSeconds must be between 1 and 3600.'
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
    $OutputPath = Join-Path $root ('tmp\phase-w-soak-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.jsonl')
}

$headers = @{}
if (-not [string]::IsNullOrWhiteSpace($SessionCookie)) {
    # Supplied through the protected process environment; never print it.
    $headers['Cookie'] = $SessionCookie
}
$started = [DateTime]::UtcNow
$deadline = $started.AddHours($DurationHours)
$samples = 0
$errors = 0
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

function Probe {
    param([string]$Name, [string]$Uri)
    $watch = [Diagnostics.Stopwatch]::StartNew()
    try {
        $response = Invoke-WebRequest -UseBasicParsing -Uri $Uri -Headers $headers -TimeoutSec 10
        $watch.Stop()
        return [pscustomobject]@{
            name = $Name; status = [int]$response.StatusCode
            durationMs = $watch.Elapsed.TotalMilliseconds; error = $null
        }
    } catch {
        $watch.Stop()
        return [pscustomobject]@{
            name = $Name; status = $null
            durationMs = $watch.Elapsed.TotalMilliseconds; error = $_.Exception.Message
        }
    }
}

Write-Output "Safe read-only soak is configured for $DurationHours hour(s); output: $OutputPath"
while ([DateTime]::UtcNow -lt $deadline) {
    $sample = @(
        Probe -Name 'health' -Uri ($ApiBaseUrl.TrimEnd('/') + '/v1/health')
        Probe -Name 'metrics' -Uri ($ApiBaseUrl.TrimEnd('/') + '/v1/metrics')
    )
    if (-not [string]::IsNullOrWhiteSpace($SessionCookie)) {
        $sample += Probe -Name 'pos-line-add-proxy' -Uri (
            $ApiBaseUrl.TrimEnd('/') + '/v1/inventory/availability?itemLegacyId=' +
            [Uri]::EscapeDataString($ItemLegacyId) + '&godownId=' + [Uri]::EscapeDataString($GodownId))
        $sample += Probe -Name 'heavy-stock-report-proxy' -Uri (
            $ApiBaseUrl.TrimEnd('/') + '/v1/reports/stock?page=1&pageSize=25&from=1900-01-01&to=2999-12-31&godownId=' +
            [Uri]::EscapeDataString($GodownId))
        $sample += Probe -Name 'finance-journals-proxy' -Uri (
            $ApiBaseUrl.TrimEnd('/') + '/v1/finance/journals?limit=25')
    }
    $record = [pscustomobject]@{
        at = [DateTime]::UtcNow.ToString('o')
        samples = $samples
        postTraffic = 'not_run'
        note = 'No document writes are generated by this safe soak. Use a disposable API/DB and an approved write fixture for post testing.'
    }
    Add-Content -LiteralPath $OutputPath -Value ($record | ConvertTo-Json -Compress)
    $samples++
    foreach ($entry in $sample) {
        if ($entry.error) { $errors++ }
    }
    Start-Sleep -Seconds $IntervalSeconds
}

[pscustomobject]@{
    status = 'completed'
    startedAt = $started.ToString('o')
    finishedAt = [DateTime]::UtcNow.ToString('o')
    configuredHours = $DurationHours
    samples = $samples
    errors = $errors
    artifact = $OutputPath
    postTraffic = 'not_run'
} | ConvertTo-Json
